### ISSUE TITLE
Method to determine last state

### ISSUE THREAD

**Issue by Xenoamor** [andrew-gresyk/HFSM2#6]
Is there any way to fetch the last state in a state's `enter()` function?

**Comment by andrew-gresyk** [comment]
Yes and no.
In a hierarchy - there's not one active state, but an edge from the root to
a leaf state.

If there's an orthogonal region - active edge 'forks-off' at that region.

With #define HFSM_ENABLE_STRUCTURE_REPORT, const ActivityHistory&
activityHistory() const is available on the FSM root.

It gives a table, stateID -> stateAge (char)

If age is 0 - the state got activated during the current update.
Positive - number of updates since it became active, caps at MAX_CHAR
Negative - number of updates since it became inactive, caps at MIN_CHAR

activityHistory() should probably go under its own #define, let me know if
that's critical for you, can easily be changed.

**Comment by Xenoamor** [comment]
Cheers for the great input @andrew-gresyk! I think I might be better off opting for a flat structure for my application

**Comment by andrew-gresyk** [comment]
I'm biased, and I believe most FSMs need more hierarchy! :)

What you want can easily be implemented in HFSM2 manually, consider the following pseudo-code:

1: Add a variable to store the last state to your context:
```cpp
struct Context {
	// ..
	hfsm2::StateID lastStateId;
};
```

2. For every state you want to track, record itself in the ```Context::lastStateId```:
```cpp
struct State
	: FSM::State
{
	void exit(PlanControl& control) {
		control.lastStateId = control.stateId();
	}
};
```

3. Check for the recorded id:
```cpp
struct State
	: FSM::State
{
	void entryGuard(GuardControl& control) {
		if (control.lastStateId == control.stateId<TSomeState>())
			// ..
	}
};
```

It is also possible (and recommended) to extract the recording into a state injection for reuse:

1. Define an injection:

```cpp
struct LastStateTracker
	: public FSM::Injection
{
	void postExit(Context& context) {
		control.lastStateId = control.stateId();
	}
};
```

Then use it as in the tracked states:

```cpp
struct Step1
	: FSM::StateT<LastStateTracker>
{
	// ..
};
```

**Comment by andrew-gresyk** [comment]
Sometimes when dealing with FSMs, it requires a change of thinking.

If you want to describe what you want to achieve, I might be able to recommend a clean way to implement that using HFSM2.
